language: cpp

addons:
    apt:
      packages:
        - python3
        - python3-pip
        - python3-setuptools
        - python3-wheel

compiler:
    - clang
    - gcc

install:
    # Use Conan to install dependencies
    - pip3 install -U pip conan --user
    - conan profile new --detect default
    - conan profile show default

script: 
    - mkdir _build && cd _build
    - conan install ../.ci/conanfile.txt -s build_type=Release
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=$(pwd)
    - cmake --build .
