language: cpp

compiler:
    - clang
    - gcc

install:
    - python3 --version
    - pip3 --version
    - pip3 install conan --user
    - conan profile show defalt
    - conan install boost/1.72.0@ -s build_type=Release -o boost:shared=True

script: 
    - mkdir _build && cd _build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
