language: cpp

addons:
    apt:
      packages:
        - python3
        - python3-pip
        - python3-setuptools
        - python3-wheel

matrix:
    include:
        - os: linux
          compiler: gcc
          before_script:
            - conan profile update settings.compiler.libcxx=libstdc++11 default
    
        - os: linux
          compiler: clang

        - os: osx
          osx_image: xcode11.3
          env:
            - CC=clang
            - CXX=clang++
    

before_install:
    - pip3 install -U pip virtualenv
    - virtualenv -p python3 ~/venv
    - source ~/venv/bin/activate

install:
    # Use Conan to install dependencies
    - pip3 install -U conan
    - conan profile new --detect default

script: 
    - mkdir build && cd build
    - travis_wait conan install ../.ci/conanfile.txt -s compiler.cppstd=11 -s build_type=Release --build missing > build.log
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=$(pwd)
    - cmake --build .
