language: cpp

addons:
    apt:
      packages:
        - python3
        - python3-pip
        - python3-setuptools

compiler:
    - clang
    - gcc

install:
    # Use Conan to install dependencies
    - pip3 install conan --user
    - conan profile show default

script: 
    - mkdir _build && cd _build
    - conan install ../.ci/conanfile.txt -s build_type=Release
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
