image: Visual Studio 2019

install:
    - C:\Python38-x64\python --version
    - set PATH=C:\Python38-x64\Scripts;%PATH%
    - C:\Python38-x64\python -m pip install conan

before_build:
    - conan profile new --detect default

build_script:
    - mkdir build && cd build
    - conan install ../.ci/conanfile.txt -s build_type=Release
    - cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=%cd:\=/%
    - nmake install
