image: Visual Studio 2017

install:
    - C:\Python38-x64\python --version
    - set PATH=C:\Python38-x64\Scripts;%PATH%
    - C:\Python38-x64\python -m pip install conan

before_build:
    - conan profile new --detect default

build_script:
    - mkdir build && cd build
    - conan install ../.ci/conanfile.txt -s compiler.cppstd=11 -s build_type=Release --build missing
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=%cd:\=/%
    - nmake install
